declare const styles: {
    managerTab: string;
    container: string;
    row: string;
    column: string;
    'ms-Grid': string;
    title: string;
    subTitle: string;
    description: string;
    SetDisplay: string;
    iconSize: string;
    overFlowCheck: string;
    tableSet: string;
    dropdownStyle: string;
    smallBox: string;
    setMainBox: string;
    SetMainTitle: string;
    nav: string;
    'bg-red': string;
    callout: string;
    'callout-danger': string;
    'alert-danger': string;
    'alert-error': string;
    'label-danger': string;
    'modal-danger': string;
    'modal-body': string;
    'bg-orange': string;
    'bg-green': string;
    'bg-blue': string;
    badge: string;
    'pull-right': string;
    block: string;
    button: string;
    label: string;
};
export default styles;
//# sourceMappingURL=ManagerTab.module.scss.d.ts.map