define([], function() {
  return {
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "MyIssuesLabel":"My Issues",
    "RequestedIssuesLabel":"Requested Issues",
    "AssignedIssuesLabel":"Assigned Issues",
    "DispatcherViewLabel":"Dispatcher View",
    "NewTicketLabel":"Raise a new request",
    "ManagerViewLabel":"Manager View",
    "WelcomeLabel":"Welcome to Departmental Request Facility!!",
    "AssignedTicketsLabel":"Assigned Tickets",
    "DepartmentBasedCardLabel":"Department based cards",
    "InProcessLabel":"In Process",
    "OpenRequestsLabel":"Open Requests",
    "PendingLabel":"Pending",
    "ClosedLabel":"Closed",
    "TotalLabel":"Total",
    "SubmitButtonLabel":"Submit",
    "TicketNumberLabel":"Ticket Number",
    "RaisedByLabel":"Raised By",
    "IssueDateLabel":"Issue Date",
    "DescriptionLabel":"Description",
    "CategoryLabel":"Category",
    "CommentLabel":"Comment",
    "ActionLabel":"Action",
    "AttachmentFromRequesterLabel":"Attachment From Requester",
    "AttachmentFromDispatcherLabel":"Attachment From Dispatcher",
    "AddFileLabel":"Add file, if any",
    "AssignToLabel":"Assign To",
    "UpdateLabel":"Update",
  }
});