declare interface IDepartmentalRequestWebPartStrings {
  PropertyPaneDescription: string;
  BasicGroupName: string;
  DescriptionFieldLabel: string;
  LoadingLabel:string;
  MyIssuesLabel:string;
  RequestedIssuesLabel:string;
  AssignedIssuesLabel:string;
  DispatcherViewLabel:string;
  NewTicketLabel:string;
  ManagerViewLabel:string;
  WelcomeLabel:string;
  AssignedTicketsLabel:string;
  DepartmentBasedCardLabel:string;
  OpenRequestsLabel:String;
  PendingLabel:string;
  InProcessLabel:string;
  ClosedLabel:string;
  CompletedLabel:string;
  TotalLabel:string;
  SubmitButtonLabel:string;
  TicketNumberLabel:string;
  RaisedByLabel:string;
  IssueDateLabel:string;
  DescriptionLabel:string;
  CategoryLabel:string;
  CommentLabel:string;
  ActionLabel:string;
  AttachmentFromRequesterLabel:string;
  AttachmentFromDispatcherLabel:string;
  AddFileLabel:string;
  AssignToLabel:string;
  UpdateLabel:string;
  DepartmentLabel:string;
  StatusLabel:string;
  DispatcherGroupLabel:string;
  ReAssignToLabel:string;
  AttachLabel:string;
  HomeLabel:string;
  NavigateBackLabel:string;
  ReminderPersonLabel:string;
  RequestedLabel:string;
  SettingsLabel:string;
  TicketLabel:string;
  AssignLabel:string;
  AllLabel:string;
  ViewAllLabel:string;
  SaveLabel:string;
  NoDataPresentLabel:string;
  RaisedANewRequestLabel:string;
  SelectDepartmentLabel:string;
  SelectTheDepartmentLabel:string;
  SelectDepartmentCategoryLabel:string;
  SelectTheDepartmentCategoryLabel:string;
  TypeYourIssueLabel:string;
  FileLabel:string;
}

declare module 'DepartmentalRequestWebPartStrings' {
  const strings: IDepartmentalRequestWebPartStrings;
  export = strings;
}
