define([], function() {
  return {
    CSVtemplateText: "Download csv template",
    UploadCSVlabel: "Upload Csv file",
    ExternalAPIlabel: "Enter API/Webservice URL",
    TeamsIconlabel: "Show Teams Icon",
    GroupName: "Birthday/Anniversary Web Part Settings",
    DropDownlabel: "Select the source from where data to be fetched for users.",
    GroupNameAdmin: "Admin Settings",
    LinkTextImage: "Add Birthday and Anniversary Images",
    LinkTextUsers: "Add Users to list to be displayed on widget",
    webpartHeading: "Birthday/Anniversary",
    birthdayBtnText: "Birthday",
    anniversaryBtnText: "Anniversary",
    helpContent: "User Help",
    configureContent: "Configure Properties",
    settingsPanelHeading: "Birthday/Anniversary Web Part Settings",
    settingsPanelDescription: "Birthday/Anniversary Web Part Settings",
    settingsPanelDropdownLabel: "Select the source from where data to be fetched for users",
    sendEmailTooltipContent: "Send Email",
    sendMessageTooltipContent: "Send message in Teams",
    noBirthdayText: "No Birthdays in this month.",
    noAnniversaryTet: "No Work Annversaries in this month.",
    sendMsgText: "Send Message to",
    personalMsgText: "Personal Message",
    templateText: "Select Template:",
    sendText:"Send",
    configurationListName: "ConfigurationSettings",
    userDetailsListName: "UserBirthAnniversaryDetails",
    imagesListName: "BirthdayAnniversaryImages",
    emailSenderListName: "EmailSender",
    saveText: "Save",
    cancelText: "Cancel",    
  }
});